<?php
include_once 'Autoloader.php';
?>

<html>

<head>

    <link rel="stylesheet" href="style.css">
</head>

<body>

    <h1>

        <?php
        



        $db = new dbTool();
        $infoPage = new infoPage();
        $sql =
            "SELECT ChunkID, X, Y, Type, Username, BuildingID
            FROM DirtGame.ChunkMap
            LEFT JOIN DirtGame.Users
            ON Users.UserID = ChunkMap.OwnerID
            WHERE ChunkID = " . $_GET["GridId"] . ";";
        $dataPool = $db->GetData($sql);

        $gridID = $dataPool["ChunkID"];
        $x = $dataPool["X"];
        $y = $dataPool["Y"];
        $gridType = $dataPool["Type"];
        $gridOwner = $dataPool["Username"];
        $buildingID = $dataPool["BuildingID"];



        echo 'ChunkID: ' . $gridID . '<br>';
        echo 'Chunk Coords: [' . $x . ';' . $y . ']<br>';
        echo 'Terrain Type: ' . $gridType . '<br>';
        echo 'Owner: ' . $gridOwner;

        ?>

    </h1>

    <?php

    $infoPage->CreateBuildingTable($x, $y, $buildingID);
    

    ?>
    <div>
    <!--Possible Orders list-->
    <form action="/DirtGame/Includes/Actions/CreateOrder.php" target="_blank" method="get">
        <table>

            <tr>
                <th colspan="3">Possible Orders</th>
            </tr>

            <tr>
                <th>
                    Assigned Workers
                </th>

                <th>
                    Resources
                </th>
                <th>
                    Amount
                </th>
            </tr>

            <tr>
                <td>
                    <input type="text" value="1" name="AssignWorkers" readonly>
                    <!--Read only until multiple workers can be assinged-->
                </td>
                <td>
                    <select name="Resource">
                    <?php
                    $infoPage->PrintResourceList($buildingID);
                    ?>
                    </select>
                </td>
                <td>
                    <input type="text" value="1" name="Amount">
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <input type="submit"></input>
                </td>
            <tr>

        </table>
    </form>
</div>
</body>

</html>