<?php
include_once 'Autoloader.php';
$Logon = new Logon();
?>

<head>
    <title>Login</title>
</head>

<div>
    <form action= "Logon.phtml" method="post">
        <label for= "Email: "> Email:</label><br>
        <input type="text" name = "Email"><br>
        <label for= "Password: "> Password:</label><br>
        <input type="password" name = "Password"><br><br>
        <input type = submit>
    
    </form>
</div>

<div>
<?php
if ($_POST["Email"] == null && $_POST["Password"] == null){
    echo 'You need to fill out the fields!';
}
else{
    echo "Loggin' you in... <br>";

    $Logon->Login($_POST["Email"],$_POST["Password"]);
    
}


?>
</div>


<div>
    <a href="/DirtGame/UI/WelcomePage.phtml">Back to Main Menu</a>
</div>
</body>