<?php
include_once 'Autoloader.php';


$db = new dbTool();

$Extract = $db->GetPureData("SELECT 
NOW(), ADDTIME(startingTime, OrderTime) AS 'FinnishTime',idOrders
FROM
DirtGame.Orders;");



while ($row = $Extract->fetch_assoc()) {

    echo $row["NOW()"] . ', ' . $row["FinnishTime"] . ', ' . $row["idOrders"] . ' == ';

    if ($row["NOW()"] >= $row["FinnishTime"]) {
        echo "fuck";
    }
    echo '<br>';
}
